# Generated by Django 4.1.5 on 2023-01-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Download rezume title')),
                ('title_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Download rezume title')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Download rezume title')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Download rezume title')),
            ],
        ),
        migrations.AddField(
            model_name='filehandler',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Reyzumi ni Tili va nomi'),
        ),
        migrations.AddField(
            model_name='filehandler',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Reyzumi ni Tili va nomi'),
        ),
        migrations.AddField(
            model_name='filehandler',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Reyzumi ni Tili va nomi'),
        ),
        migrations.AddField(
            model_name='filehandler',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Reyzumi ni Tili va nomi'),
        ),
    ]
