# Generated by Django 4.1.5 on 2023-01-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0002_downloadfile_filehandler_title_filehandler_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filehandler',
            name='btn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tugma tili'),
        ),
        migrations.AddField(
            model_name='filehandler',
            name='btn_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tugma tili'),
        ),
        migrations.AddField(
            model_name='filehandler',
            name='btn_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tugma tili'),
        ),
        migrations.AddField(
            model_name='filehandler',
            name='btn_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tugma tili'),
        ),
    ]
