# Generated by Django 4.1.5 on 2023-01-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_rename_email_contactbody_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactbody',
            name='website_link',
            field=models.CharField(blank=True, default='https://abrorbek.com', max_length=255, null=True, verbose_name='Wesite link'),
        ),
    ]
