# Generated by Django 4.1.5 on 2023-01-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_contactbody_website_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactbody',
            name='body',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="So'rovnoma haqida"),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='body_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="So'rovnoma haqida"),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='body_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="So'rovnoma haqida"),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='body_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="So'rovnoma haqida"),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email adress'),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='email_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email adress'),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='email_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email adress'),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='email_send',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Input email nomi'),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='email_send_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Input email nomi'),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='email_send_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Input email nomi'),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='email_send_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Input email nomi'),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='email_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email adress'),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Office joylashuvi'),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='location_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Office joylashuvi'),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='location_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Office joylashuvi'),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='location_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Office joylashuvi'),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='message',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Email yuborish izohi'),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='message_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Email yuborish izohi'),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='message_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Email yuborish izohi'),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='message_send',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Input message nomi'),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='message_send_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Input message nomi'),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='message_send_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Input message nomi'),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='message_send_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Input message nomi'),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='message_uz',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Email yuborish izohi'),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Input shaxs nomi nomi'),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Input shaxs nomi nomi'),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='name_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Input shaxs nomi nomi'),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='name_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Input shaxs nomi nomi'),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='office',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Office sarlavhasi'),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='office_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Office sarlavhasi'),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='office_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Office sarlavhasi'),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='office_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Office sarlavhasi'),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefon sarlavhasi'),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='phone_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefon sarlavhasi'),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='phone_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefon sarlavhasi'),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='phone_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefon sarlavhasi'),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='send_email',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name="Xabar yuborish bo'limi"),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='send_email_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name="Xabar yuborish bo'limi"),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='send_email_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name="Xabar yuborish bo'limi"),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='send_email_uz',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name="Xabar yuborish bo'limi"),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='send_message',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Input Send Message nomi'),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='send_message_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Input Send Message nomi'),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='send_message_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Input Send Message nomi'),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='send_message_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Input Send Message nomi'),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Input subject nomi'),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='subject_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Input subject nomi'),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='subject_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Input subject nomi'),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='subject_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Input subject nomi'),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Saytni so'rovnomasi"),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Saytni so'rovnomasi"),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Saytni so'rovnomasi"),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Saytni so'rovnomasi"),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='website_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='website_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='contactbody',
            name='website_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='contacttitle',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sayt sarlavhasi'),
        ),
        migrations.AlterField(
            model_name='contacttitle',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sayt sarlavhasi'),
        ),
        migrations.AlterField(
            model_name='contacttitle',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sayt sarlavhasi'),
        ),
        migrations.AlterField(
            model_name='contacttitle',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sayt sarlavhasi'),
        ),
    ]
