# Generated by Django 4.1.5 on 2023-01-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_contactbody_body_alter_contactbody_body_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactComplite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name="Ma'lumot olnigani haqida xabar berish")),
                ('title_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name="Ma'lumot olnigani haqida xabar berish")),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name="Ma'lumot olnigani haqida xabar berish")),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name="Ma'lumot olnigani haqida xabar berish")),
                ('body', models.CharField(blank=True, max_length=255, null=True, verbose_name="Olingan ma'lumot haqida xabar berish")),
                ('body_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name="Olingan ma'lumot haqida xabar berish")),
                ('body_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name="Olingan ma'lumot haqida xabar berish")),
                ('body_en', models.CharField(blank=True, max_length=255, null=True, verbose_name="Olingan ma'lumot haqida xabar berish")),
            ],
        ),
    ]
