# Generated by Django 4.1.5 on 2023-01-24 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApiFilter',
            new_name='PostFilter',
        ),
    ]
