# Generated by Django 4.1.6 on 2023-02-07 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_rest', '0003_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
