# Generated by Django 4.1.5 on 2023-01-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Sayt sarlavhasi')),
                ('title_uz', models.CharField(blank=True, max_length=250, null=True, verbose_name='Sayt sarlavhasi')),
                ('title_ru', models.CharField(blank=True, max_length=250, null=True, verbose_name='Sayt sarlavhasi')),
                ('title_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='Sayt sarlavhasi')),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Ism sharf')),
                ('name_uz', models.CharField(blank=True, max_length=300, null=True, verbose_name='Ism sharf')),
                ('name_ru', models.CharField(blank=True, max_length=300, null=True, verbose_name='Ism sharf')),
                ('name_en', models.CharField(blank=True, max_length=300, null=True, verbose_name='Ism sharf')),
                ('work', models.CharField(blank=True, max_length=255, null=True, verbose_name='ish bilan tanishtirish')),
                ('work_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='ish bilan tanishtirish')),
                ('work_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='ish bilan tanishtirish')),
                ('work_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='ish bilan tanishtirish')),
                ('work_title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Ish nomi')),
                ('work_title_uz', models.CharField(blank=True, max_length=300, null=True, verbose_name='Ish nomi')),
                ('work_title_ru', models.CharField(blank=True, max_length=300, null=True, verbose_name='Ish nomi')),
                ('work_title_en', models.CharField(blank=True, max_length=300, null=True, verbose_name='Ish nomi')),
                ('body', models.CharField(blank=True, max_length=800, null=True, verbose_name="Men haqimda qisqa ma'lumot")),
                ('body_uz', models.CharField(blank=True, max_length=800, null=True, verbose_name="Men haqimda qisqa ma'lumot")),
                ('body_ru', models.CharField(blank=True, max_length=800, null=True, verbose_name="Men haqimda qisqa ma'lumot")),
                ('body_en', models.CharField(blank=True, max_length=800, null=True, verbose_name="Men haqimda qisqa ma'lumot")),
                ('image', models.ImageField(upload_to='home/')),
                ('download', models.CharField(blank=True, max_length=255, null=True, verbose_name='Download CV')),
                ('download_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Download CV')),
                ('download_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Download CV')),
                ('download_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Download CV')),
            ],
        ),
        migrations.CreateModel(
            name='MenuPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sayt bosh harfi')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sayt sarlavhasi')),
                ('home', models.CharField(blank=True, max_length=200, null=True, verbose_name="sayt menu_bar home-page bo'limi")),
                ('home_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name="sayt menu_bar home-page bo'limi")),
                ('home_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name="sayt menu_bar home-page bo'limi")),
                ('home_en', models.CharField(blank=True, max_length=200, null=True, verbose_name="sayt menu_bar home-page bo'limi")),
                ('about', models.CharField(blank=True, max_length=200, null=True, verbose_name="sayt menu_bar about bo'limi")),
                ('about_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name="sayt menu_bar about bo'limi")),
                ('about_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name="sayt menu_bar about bo'limi")),
                ('about_en', models.CharField(blank=True, max_length=200, null=True, verbose_name="sayt menu_bar about bo'limi")),
                ('services', models.CharField(blank=True, max_length=200, null=True, verbose_name="sayt menu_bar servis bo'limi")),
                ('services_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name="sayt menu_bar servis bo'limi")),
                ('services_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name="sayt menu_bar servis bo'limi")),
                ('services_en', models.CharField(blank=True, max_length=200, null=True, verbose_name="sayt menu_bar servis bo'limi")),
                ('portfolio', models.CharField(blank=True, max_length=200, null=True, verbose_name="sayt menu_bar portfolio bo'limi")),
                ('portfolio_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name="sayt menu_bar portfolio bo'limi")),
                ('portfolio_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name="sayt menu_bar portfolio bo'limi")),
                ('portfolio_en', models.CharField(blank=True, max_length=200, null=True, verbose_name="sayt menu_bar portfolio bo'limi")),
                ('contact', models.CharField(blank=True, max_length=200, null=True, verbose_name="sayt menu_bar contact bo'limi")),
                ('contact_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name="sayt menu_bar contact bo'limi")),
                ('contact_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name="sayt menu_bar contact bo'limi")),
                ('contact_en', models.CharField(blank=True, max_length=200, null=True, verbose_name="sayt menu_bar contact bo'limi")),
                ('color', models.CharField(blank=True, max_length=500, null=True, verbose_name='Sayt temasi')),
                ('color_uz', models.CharField(blank=True, max_length=500, null=True, verbose_name='Sayt temasi')),
                ('color_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Sayt temasi')),
                ('color_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Sayt temasi')),
            ],
        ),
    ]
