# Generated by Django 4.1.6 on 2023-03-18 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_1', models.CharField(blank=True, max_length=255, null=True)),
                ('color_2', models.CharField(blank=True, max_length=255, null=True)),
                ('color_3', models.CharField(blank=True, max_length=255, null=True)),
                ('color_4', models.CharField(blank=True, max_length=255, null=True)),
                ('color_5', models.CharField(blank=True, max_length=255, null=True)),
                ('color_6', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
