# Generated by Django 4.1.5 on 2023-01-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Sarlavha ')),
                ('title_uz', models.CharField(blank=True, max_length=300, null=True, verbose_name='Sarlavha ')),
                ('title_ru', models.CharField(blank=True, max_length=300, null=True, verbose_name='Sarlavha ')),
                ('title_en', models.CharField(blank=True, max_length=300, null=True, verbose_name='Sarlavha ')),
                ('information', models.CharField(blank=True, max_length=400, null=True, verbose_name="Ma'lumot")),
                ('information_uz', models.CharField(blank=True, max_length=400, null=True, verbose_name="Ma'lumot")),
                ('information_ru', models.CharField(blank=True, max_length=400, null=True, verbose_name="Ma'lumot")),
                ('information_en', models.CharField(blank=True, max_length=400, null=True, verbose_name="Ma'lumot")),
            ],
        ),
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='About Sahifasi')),
                ('title_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='About Sahifasi')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='About Sahifasi')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='About Sahifasi')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ism Sharf')),
                ('name_uz', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ism Sharf')),
                ('name_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ism Sharf')),
                ('name_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ism Sharf')),
                ('work_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Work name')),
                ('work_name_uz', models.CharField(blank=True, max_length=500, null=True, verbose_name='Work name')),
                ('work_name_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Work name')),
                ('work_name_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Work name')),
                ('body', models.CharField(blank=True, max_length=800, null=True, verbose_name="Men haqimda ma'lumot")),
                ('body_uz', models.CharField(blank=True, max_length=800, null=True, verbose_name="Men haqimda ma'lumot")),
                ('body_ru', models.CharField(blank=True, max_length=800, null=True, verbose_name="Men haqimda ma'lumot")),
                ('body_en', models.CharField(blank=True, max_length=800, null=True, verbose_name="Men haqimda ma'lumot")),
            ],
        ),
        migrations.CreateModel(
            name='EducationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.CharField(blank=True, max_length=200, null=True, verbose_name='Yaratilgan sana')),
                ('title', models.CharField(blank=True, max_length=555, null=True, verbose_name="O'qigan joy nomi")),
                ('title_uz', models.CharField(blank=True, max_length=555, null=True, verbose_name="O'qigan joy nomi")),
                ('title_ru', models.CharField(blank=True, max_length=555, null=True, verbose_name="O'qigan joy nomi")),
                ('title_en', models.CharField(blank=True, max_length=555, null=True, verbose_name="O'qigan joy nomi")),
                ('body', models.CharField(blank=True, max_length=1000, null=True, verbose_name="O'qigan joydan ma'lumot")),
                ('body_uz', models.CharField(blank=True, max_length=1000, null=True, verbose_name="O'qigan joydan ma'lumot")),
                ('body_ru', models.CharField(blank=True, max_length=1000, null=True, verbose_name="O'qigan joydan ma'lumot")),
                ('body_en', models.CharField(blank=True, max_length=1000, null=True, verbose_name="O'qigan joydan ma'lumot")),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.CharField(blank=True, max_length=200, null=True, verbose_name='Yaratilgan sana')),
                ('title', models.CharField(blank=True, max_length=555, null=True, verbose_name="O'qigan joy nomi")),
                ('title_uz', models.CharField(blank=True, max_length=555, null=True, verbose_name="O'qigan joy nomi")),
                ('title_ru', models.CharField(blank=True, max_length=555, null=True, verbose_name="O'qigan joy nomi")),
                ('title_en', models.CharField(blank=True, max_length=555, null=True, verbose_name="O'qigan joy nomi")),
                ('body', models.CharField(blank=True, max_length=1000, null=True, verbose_name="O'qigan joydan ma'lumot")),
                ('body_uz', models.CharField(blank=True, max_length=1000, null=True, verbose_name="O'qigan joydan ma'lumot")),
                ('body_ru', models.CharField(blank=True, max_length=1000, null=True, verbose_name="O'qigan joydan ma'lumot")),
                ('body_en', models.CharField(blank=True, max_length=1000, null=True, verbose_name="O'qigan joydan ma'lumot")),
            ],
        ),
        migrations.CreateModel(
            name='ExprementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(blank=True, max_length=200, null=True, verbose_name="o'qigan joylar")),
                ('education_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name="o'qigan joylar")),
                ('education_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name="o'qigan joylar")),
                ('education_en', models.CharField(blank=True, max_length=200, null=True, verbose_name="o'qigan joylar")),
                ('experience', models.CharField(blank=True, max_length=200, null=True, verbose_name='Amalyontalar qilingan ishlar')),
                ('experience_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name='Amalyontalar qilingan ishlar')),
                ('experience_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Amalyontalar qilingan ishlar')),
                ('experience_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Amalyontalar qilingan ishlar')),
            ],
        ),
        migrations.CreateModel(
            name='HireMeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hire-Me')),
                ('title_uz', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hire-Me')),
                ('title_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hire-Me')),
                ('title_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hire-Me')),
            ],
        ),
        migrations.CreateModel(
            name='LearningModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name="O'rgangan programma tili")),
                ('name_uz', models.CharField(blank=True, max_length=100, null=True, verbose_name="O'rgangan programma tili")),
                ('name_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name="O'rgangan programma tili")),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name="O'rgangan programma tili")),
                ('witdh', models.CharField(blank=True, default='95%', max_length=100, null=True, verbose_name="O'rgangan proggramma % ")),
                ('witdh_uz', models.CharField(blank=True, default='95%', max_length=100, null=True, verbose_name="O'rgangan proggramma % ")),
                ('witdh_ru', models.CharField(blank=True, default='95%', max_length=100, null=True, verbose_name="O'rgangan proggramma % ")),
                ('witdh_en', models.CharField(blank=True, default='95%', max_length=100, null=True, verbose_name="O'rgangan proggramma % ")),
                ('skill', models.CharField(blank=True, default='95%', max_length=100, null=True, verbose_name="Foydalanuvchiga ko'rinadigan %")),
                ('skill_uz', models.CharField(blank=True, default='95%', max_length=100, null=True, verbose_name="Foydalanuvchiga ko'rinadigan %")),
                ('skill_ru', models.CharField(blank=True, default='95%', max_length=100, null=True, verbose_name="Foydalanuvchiga ko'rinadigan %")),
                ('skill_en', models.CharField(blank=True, default='95%', max_length=100, null=True, verbose_name="Foydalanuvchiga ko'rinadigan %")),
            ],
        ),
    ]
