# Generated by Django 4.1.5 on 2023-01-24 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio_category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='portfolio_project',
            name='description',
        ),
        migrations.AddField(
            model_name='portfolio_category',
            name='body',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name="Portfolio Categoryasi haqida qisqa ma'lumot"),
        ),
        migrations.AddField(
            model_name='portfolio_project',
            name='body',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name="Proyekt haqida ma'lumot"),
        ),
        migrations.AlterField(
            model_name='portfolio_category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/category', verbose_name='Portfolio Categoryasi rasmi'),
        ),
        migrations.AlterField(
            model_name='portfolio_category',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Portfolio Categorya nomi'),
        ),
        migrations.AlterField(
            model_name='portfolio_project',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio_category', verbose_name='Proyekt Categoriyasi'),
        ),
        migrations.AlterField(
            model_name='portfolio_project',
            name='image',
            field=models.ImageField(upload_to='portfolio/rest-framework', verbose_name='Proyekt rasmi'),
        ),
        migrations.AlterField(
            model_name='portfolio_project',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Proyektga ishlov berish'),
        ),
        migrations.AlterField(
            model_name='portfolio_project',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Proyekt kod link'),
        ),
        migrations.AlterField(
            model_name='portfolio_project',
            name='site_link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Proyekt link'),
        ),
        migrations.AlterField(
            model_name='portfolio_project',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Proyekt nomi'),
        ),
    ]
