# Generated by Django 4.1.5 on 2023-01-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_portfolio_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio_category',
            name='body_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name="Portfolio Categoryasi haqida qisqa ma'lumot"),
        ),
        migrations.AddField(
            model_name='portfolio_category',
            name='body_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name="Portfolio Categoryasi haqida qisqa ma'lumot"),
        ),
        migrations.AddField(
            model_name='portfolio_category',
            name='body_uz',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name="Portfolio Categoryasi haqida qisqa ma'lumot"),
        ),
        migrations.AddField(
            model_name='portfolio_category',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Portfolio Categorya nomi'),
        ),
        migrations.AddField(
            model_name='portfolio_category',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Portfolio Categorya nomi'),
        ),
        migrations.AddField(
            model_name='portfolio_category',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Portfolio Categorya nomi'),
        ),
        migrations.AddField(
            model_name='portfolio_project',
            name='body_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name="Proyekt haqida ma'lumot"),
        ),
        migrations.AddField(
            model_name='portfolio_project',
            name='body_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name="Proyekt haqida ma'lumot"),
        ),
        migrations.AddField(
            model_name='portfolio_project',
            name='body_uz',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name="Proyekt haqida ma'lumot"),
        ),
        migrations.AddField(
            model_name='portfolio_project',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Proyekt nomi'),
        ),
        migrations.AddField(
            model_name='portfolio_project',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Proyekt nomi'),
        ),
        migrations.AddField(
            model_name='portfolio_project',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Proyekt nomi'),
        ),
    ]
