# Generated by Django 4.1.5 on 2023-01-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfolio_category_body_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Portfel haqida')),
                ('title_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Portfel haqida')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Portfel haqida')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Portfel haqida')),
                ('projects', models.CharField(blank=True, max_length=300, null=True, verbose_name='Mening oxirgi loyihalarim')),
                ('projects_uz', models.CharField(blank=True, max_length=300, null=True, verbose_name='Mening oxirgi loyihalarim')),
                ('projects_ru', models.CharField(blank=True, max_length=300, null=True, verbose_name='Mening oxirgi loyihalarim')),
                ('projects_en', models.CharField(blank=True, max_length=300, null=True, verbose_name='Mening oxirgi loyihalarim')),
            ],
        ),
    ]
