# Generated by Django 4.1.5 on 2023-01-25 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_portfoliocount'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio_project',
            name='button',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sayt kodi'),
        ),
        migrations.AddField(
            model_name='portfolio_project',
            name='button1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Saytni ko'rish"),
        ),
        migrations.AddField(
            model_name='portfolio_project',
            name='button1_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Saytni ko'rish"),
        ),
        migrations.AddField(
            model_name='portfolio_project',
            name='button1_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Saytni ko'rish"),
        ),
        migrations.AddField(
            model_name='portfolio_project',
            name='button1_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Saytni ko'rish"),
        ),
        migrations.AddField(
            model_name='portfolio_project',
            name='button_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sayt kodi'),
        ),
        migrations.AddField(
            model_name='portfolio_project',
            name='button_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sayt kodi'),
        ),
        migrations.AddField(
            model_name='portfolio_project',
            name='button_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sayt kodi'),
        ),
    ]
