# Generated by Django 4.1.5 on 2023-01-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_portfolio_project_button_portfolio_project_button1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio_project',
            name='modified',
        ),
        migrations.AddField(
            model_name='portfolio_project',
            name='created_time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Yartilgan vaqat'),
        ),
        migrations.AddField(
            model_name='portfolio_project',
            name='created_time_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Yartilgan vaqat'),
        ),
        migrations.AddField(
            model_name='portfolio_project',
            name='created_time_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Yartilgan vaqat'),
        ),
        migrations.AddField(
            model_name='portfolio_project',
            name='created_time_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Yartilgan vaqat'),
        ),
    ]
